Creado el apartado de cómo crear un Fork
WordPress/spain-handbook pull request #262
Opened 2023-12-21 09:14 UTC by AkireOrl

Se han añadido cosas y cambiado imagenes. Se ha eliminado información dirigida a ususarios con privilegios.

Revisar las rutas de las imagenes

2023-12-21 09:25 UTC, jesusyesares requested changes
Te he puesto un cambio.

2023-12-21 09:25 UTC, jesusyesares commented on manuales/github/fork/index.md
>  Nota para el editor: Aclarar que la documentación está alojada en el repositorio principal de WordPress (wordpress/spain-handbook), y que tu fork (tucuentagithub/spain-handbook) es donde se realizará
Ya he comprobado que has aclarado dónde está el repo principal y que se trabaja en el fork propio.

¿Puedes eliminar este párrafo?

2023-12-21 09:30 UTC, jesusyesares approved these changes
Aprobado

2024-01-04 13:54 UTC, moranjosep commented
Hola @nilovelez. Antes de nada Feliz 2024! Tenemos el issue #262 pendiente de revisión por parte de un GTE. 
¿Puedes revisarlo cuando tengas un momentillo a ver si podemos terminar el Project de GitHub?

Muchas gracias y un saludo!!

2024-01-11 07:41 UTC, javiercasares commented
Hay que mover las imágenes a su carpeta correspondiente y revisar que no haya comentarios dentro del artículo.

2024-01-11 07:43 UTC, javiercasares approved these changes

2024-01-13 08:29 UTC, jesusyesares commented
He intentado mover las imágenes a su carpeta correcta, pero no tengo permisos para hacer push sobre el PR, por lo que necesito que se acepte este PR, y entonces podré hacer este trabajo en mi repo.

2024-01-13 09:23 UTC, jesusyesares commented
@AkireOrl Necesito que compruebes si en tu fork del repositorio aparece un mensaje indicando que ha habido nuevos cambios. Los cambios que he realizado son estos.

![CleanShot 2024-01-13 at 10 22 29@2x](https://github.com/WordPress/spain-handbook/assets/2352123/cb4d3a5e-5d8d-4b20-951b-d6f5296fb692)

Si es así, buscamos un ratillo para lanzarlos juntos al PR principal.

2024-01-13 09:28 UTC, moranjosep approved these changes

2024-01-13 10:14 UTC, jesusyesares requested changes

2024-01-13 10:14 UTC, jesusyesares commented on manuales/github/fork/index.md
> +![Crear un Fork](https://raw.githubusercontent.com/WPES/spain-handbook/master/assets/1.crearUnFork.png)
La ruta cámbiala por https://raw.githubusercontent.com/WordPress/spain-handbook/master/assets/Fork-crear.jpg

2024-01-13 10:14 UTC, jesusyesares commented on manuales/github/fork/index.md
> +![Estamos en nuestro Fork](https://raw.githubusercontent.com/WPES/spain-handbook/master/assets/2.estamos-en-nuestro-fork.png)
La ruta cámbiala por https://raw.githubusercontent.com/WordPress/spain-handbook/master/assets/Fork-estamos-en-fork.jpg

2024-01-13 10:14 UTC, jesusyesares commented on manuales/github/fork/index.md
> +![Actualizamos Rama]([./img/](https://raw.githubusercontent.com/WPES/spain-handbook/master/assets/3.UpdateBranch.png)
La ruta cámbiala por https://raw.githubusercontent.com/WordPress/spain-handbook/master/assets/Fork-actualizar-rama.jpg

2024-01-13 10:14 UTC, jesusyesares commented on manuales/github/fork/index.md
> +![Solicitamos Pull Request](https://raw.githubusercontent.com/WPES/spain-handbook/master/assets/4.Contribute-btn-and-send-PR.png)
La ruta cámbiala por https://raw.githubusercontent.com/WordPress/spain-handbook/master/assets/Fork-contribute-send-PR.jpg

2024-01-13 10:14 UTC, jesusyesares commented on manuales/github/fork/index.md
> +![Actualizamos Rama](https://raw.githubusercontent.com/WPES/spain-handbook/master/assets/3.UpdateBranch.png)
La ruta cámbiala por https://raw.githubusercontent.com/WordPress/spain-handbook/master/assets/Fork-actualizar-rama.jpg

2024-01-13 11:48 UTC, jesusyesares approved these changes
Perfectísimo

2024-01-13 11:52 UTC, merged