#issue 243 index.md
WordPress/spain-handbook pull request #264
Opened 2024-01-06 18:54 UTC by moranjosep

Documentación enviada a la ubicación indicada. Falta poner una imagen en la descripción del apartado número 8.

2024-01-11 07:25 UTC, javiercasares approved these changes

2024-01-11 07:42 UTC, javiercasares commented
Por mí está OK.

2024-01-11 07:43 UTC, javiercasares approved these changes

2024-02-14 18:16 UTC, jesusyesares requested changes
Adjuntar foto en el apartado 8

2024-02-23 14:56 UTC, nilovelez approved these changes
todo ok

2024-02-29 09:40 UTC, jesusyesares approved these changes

2024-02-29 09:41 UTC, merged