como sincronizar un fork. (Fetch)
WordPress/spain-handbook pull request #297
Opened 2024-04-12 10:04 UTC by pilargarciaab

2024-04-12 10:08 UTC, pilargarciaab commented
Perdón, he subido las imágenes a assets, pero no he modificado la ruta en el artículo.

2024-04-25 11:57 UTC, moranjosep requested changes
Hola Pilar. Te he añadido pequeñas correcciones y las normas de los nombres de archivo. El resto ok.
Un saludo!

2024-04-25 11:57 UTC, moranjosep commented on manuales/github/fetch/index.md
> +-
Elimina esta entrada de lista.
Un saludo!

2024-04-25 11:57 UTC, moranjosep commented on manuales/github/fetch/index.md
> +Antes de empezar a trabajar en cualquier fork, es necesario sincronizarlo (actualizarlo) con el repositorio principal. Esto te asegurará que estás trabajando sobre la última versión.
Debes insertar un espacio entre epígrafes.
Un saludo!

2024-04-25 11:57 UTC, moranjosep commented on manuales/github/fetch/index.md
> +Para ello:
Debes insertar un espacio.
Un saludo!

2024-04-25 11:57 UTC, moranjosep commented on assets/Título del repositorio.webp
Los nombres de archivos no pueden contener espacios ni carácter alguno que no sea letra, número o guion a cambio de un espacio. Merci y un saludo!

2024-04-25 11:57 UTC, moranjosep commented on assets/botón sincronizar rama.webp
Los nombres de archivos no pueden contener espacios ni carácter alguno que no sea letra, número o guion a cambio de un espacio. Merci y un saludo!

2024-05-02 16:33 UTC, pilargarciaab commented on assets/Título del repositorio.webp
gracias. Necesito que me pongáis la ruta completa de la imagen, para saber de cuál se trata.

2024-05-10 11:19 UTC, closed without merging