Creada la página del equipo de documentación
WordPress/spain-handbook pull request #325
Opened 2024-05-08 16:30 UTC by jesusyesares

He creado la página de presentación del equipo de documentación.

2024-05-08 16:33 UTC, moranjosep approved these changes
Todo ok.  Falta revisar por @nilovelez

2024-05-08 22:30 UTC, nilovelez requested changes
Me rechina un poco lo de "las personas usuarias de WordPress", no se me ocurre ninguna forma mejor de ponerlo.

"¿Cómo colaborar en el equipo de documentación de WordPress español?" habría que cambiarlo por:
"¿Cómo colaborar con el equipo español de documentación de WordPress?"

2024-05-14 11:19 UTC, jesusyesares commented
¿Qué te parece "las personas que con perfil de usuario en WordPress"?

A lo otro ok.

2024-05-14 11:25 UTC, nilovelez commented
Yo lo pondría directamente:
"El equipo de documentación trabaja para **crear materiales de consulta** tanto para los usuarios finales de WordPress como para quien quiera colaborar con los equipos que hacen posible WordPress."

2024-05-14 12:10 UTC, jesusyesares reviewed
Me parece perfecto.

2024-05-14 12:13 UTC, merged