Manual de eventos sostenibles
WordPress/spain-handbook pull request #356
Opened 2024-10-09 08:55 UTC by CeliGaroe

¡Hola! He creado un fork del spain-handbook para añadir[ la traducción del manual de eventos sostenibles](https://docs.google.com/document/d/1K28caiJrpn8pTXheMTV0w7NBwee5kJ7_tX6igghaOdE/edit) publicado en el [equipo de sostenibilidad global](https://make.wordpress.org/sustainability/handbook/sustainable-events/) ([enlace GitHub](https://github.com/WordPress/sustainability/tree/trunk/events)) aplicando las anotaciones que nos dejó @nilovelez en el documento de traducción. 

La idea es publicarlo [tal y como está en dicho equipo](https://make.wordpress.org/sustainability/handbook/sustainable-events/), con la página 'Manual de eventos sostenibles' como la madre, y el resto de secciones como subpáginas: 

![Captura de pantalla 2024-10-09 a las 10 54 08](https://github.com/user-attachments/assets/4350751f-3fc6-46a8-b32e-10e10d953045)

Una vez revisado y publicado, crearé un pull request secundario para añadir los enlaces internos correspondientes (entre subsecciones del manual). 

Si he hecho algo mal o necesitáis más información, soy toda oídos. :) ¡Gracias!

2024-10-09 08:56 UTC, CeliGaroe commented
@moranjosep Aquí está el manual de eventos sostenibles. :)

2024-10-10 05:09 UTC, javiercasares commented
LGTM.

Como tiene que ver con los eventos, recordad hacer un cruce co los manuales de marketing de eventos para que se tenga en cuenta.

2024-10-21 17:37 UTC, jesusyesares requested changes
Hola @CeliGaroe, he marcado un par de cosillas, una pequeña (supuesta) errata y una cosa que hay que confirmar. Revisadla porfa.

Por lo demás, está para aprobar.

2024-10-21 17:37 UTC, jesusyesares commented on sostenibilidad/eventos/catering.md
> +  - Es un negocio local, que cocina comida de la zona, usa ingredientes locales y que idealmente elabora menús de temporada. También es recomendable    - que use productos de comercio justo, orgánico
Este guión no sé muy bien si va en un salto de página o si se ha escapado.

2024-10-21 17:37 UTC, jesusyesares commented on sostenibilidad/eventos/regalos.md
> +WordCamp Central te proporcionará [cintas para las acreditaciones y otros materiales de oficina](https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/supplies/) que pueda
Si no me equivoco, esto ya no es así. Confirmadlo.

2024-10-21 17:57 UTC, CeliGaroe commented
> Hola @CeliGaroe, he marcado un par de cosillas, una pequeña (supuesta) errata y una cosa que hay que confirmar. Revisadla porfa.
> 
> Por lo demás, está para aprobar.

¡Gracias, @jesusyesares! Todo revisado y corregido. :)

2024-10-21 18:04 UTC, jesusyesares submitted a review, later dismissed
Todo correcto :)

2024-10-21 18:06 UTC, jesusyesares commented
@nilovelez ¿Puedes darle tu revisión a esto?

2024-10-23 18:06 UTC, javiercasares commented
@CeliGaroe en la página principal del manual, debería haber una lista, y sea en plan lista, o explicado, o como sea, que enlace a cada una de las secciones del manual. No se puede dejar la navegación exclusivamente al menú.

2024-10-24 16:24 UTC, CeliGaroe commented
> @CeliGaroe en la página principal del manual, debería haber una lista, y sea en plan lista, o explicado, o como sea, que enlace a cada una de las secciones del manual. No se puede dejar la navegación exclusivamente al menú.

De acuerdo, @javiercasares. En el global no necesitamos que esté así, pero entiendo que las normas de este manual son distintas. Yo pongo la lista sin problema en la página principal, pero los enlaces tendré que ponerlos cuando esté todo publicado y pueda asegurarme de que el enlace que pongo es el correcto, ¿no? Me confirmas y con eso lo hago. ¡Gracias!

2024-10-24 16:27 UTC, javiercasares commented
Si quieres poner enlaces relativos, me sirve… aún no está clara (supongo que en el CD de la WCGRX se decidirá) la estructura final, por lo que ya haré yo los ajustes previos a la publicación de ese elemento en concreto (y si hay otros enlaces por el manual, también los corregiré).

No hace falta que escribáis un párrafo con enlaces; si queréis ponerlos en modo lista, también sirve. Algo en plan:

- Lo que sea: aquí vas a encontrar esto
- Lo otro: aquí vas a encontrar lo otro.

2024-10-24 16:51 UTC, CeliGaroe commented
@javiercasares Ya he añadido la lista y añadido todos los enlaces que deberían enlazar entre las subpáginas (temporales, hasta que se confirme si ese es el enlace correcto o no).

2024-10-24 16:54 UTC, javiercasares commented
Perfecto. Ya te digo, no te preocupes por los enlaces porque eso es lo ultimísimo que se revisa antes de cualquier subida a publicación.

2024-10-24 16:57 UTC, jesusyesares submitted a review, later dismissed

2024-10-25 07:30 UTC, javiercasares commented
Relacionado: #364

2024-10-25 10:01 UTC, javiercasares commented
Depende de: #366

2024-10-27 06:27 UTC, javiercasares commented
Se ha actualizado la estructura de URL sobre el #364 y #366.

2024-10-27 06:30 UTC, javiercasares submitted a review, later dismissed

2024-10-28 06:43 UTC, merged